name: CI

on: [push]

jobs:
 sast_scan:
   name: run_bandit scan 
   runs-on: ubuntu-latest

   steps:
   - name: checkout code 
     uses: actions/checkout@v2

   - name: install python 
     uses: actions/setup-python@v2
     with:
          python-version: 3.8
          
   -  name: Install bandit
      run: pip install bandit

   -  name: Run bandit scan
      run: bandit -ll -ii -r . -f json -o bandit_report.json

   -  name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
         name: bandit_findings
         path: bandit_report.json

 image_scan:
         name: Build image and run image scan  
         runs-on: ubuntu-latest

         steps:
          - name: checkout code 
            uses: actions/checkout@v2

          - name: Set up docker
            uses: docker-practice/actions-setup-docker@v1
            with:
              docker_version: '20.10'
          - name: Build Docker Image
            run: docker build -f Dockerfile -t myapp:latest .
            
          - name: docker scout scan
            run: |
                 curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
                 sh install-scout.sh
                 docker scout quickview
                 docker scout cves
            

          
               
